
index:
    path: /
    controller: App\Controller\UserController::formConnexion

#test
test:
  path: /test
  controller: App\Controller\DefaultController::test

#Création utilisateur
createUser:
  path: /user/create
  controller: App\Controller\UserController::createUser

#Formulaire création utilisateur
formCreateUser:
  path: /user/create/form
  controller: App\Controller\UserController::formCreateUser

#Liste utilisateurs
listUser:
  path: /user/list
  controller: App\Controller\UserController::listUser

#Liste utilisateurs
deleteUser:
  path: /user/delete/{id}
  controller: App\Controller\UserController::deleteUser

#Connexion
connexion:
  path: /connexion
  controller: App\Controller\UserController::connexion

#Deconnexion
deconnexion:
  path: /deconnexion
  controller: App\Controller\UserController::deconnexion

#Formulaire connexion
formConnexion:
  path: /connexion/form
  controller: App\Controller\UserController::formConnexion

#Création fonction
createFonction:
  path: /fonction/create
  controller: App\Controller\FonctionController::createFonction

#Formulaire création fonction
formCreateFonction:
  path: /fonction/create/form
  controller: App\Controller\FonctionController::formCreateFonction

#Liste fonctions
listFonction:
  path: /fonction/list
  controller: App\Controller\FonctionController::listFonction

#Archive fonction
archiveFonction:
  path: /fonction/archive/{id}
  controller: App\Controller\FonctionController::archiveFonction

#Liste annuaire
listAnnuaire:
  path: /annuaire/list
  controller: App\Controller\AnnuaireController::listAnnuaire

#Formulaire création contact
formCreateContact:
  path: /annuaire/create/form
  controller: App\Controller\AnnuaireController::formCreateContact

#Création contact
createContact:
  path: /annuaire/create
  controller: App\Controller\AnnuaireController::createContact

#Détails contact
showContact:
  path: /annuaire/show/{id}
  controller: App\Controller\AnnuaireController::showContact

#Archive contact
archiveContact:
  path: /annuaire/archive/{id}
  controller: App\Controller\AnnuaireController::archiveContact