#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#test
test:
  path: /test
  controller: App\Controller\DefaultController::test

#Création utilisateur
createUser:
  path: /user/create
  controller: App\Controller\UserController::createUser

#Formulaire création utilisateur
formCreateUser:
  path: /user/create/form
  controller: App\Controller\UserController::formCreateUser

#Liste utilisateurs
listUser:
  path: /user/list
  controller: App\Controller\UserController::listUser

#Connexion
connexion:
  path: /connexion
  controller: App\Controller\UserController::connexion

#Formulaire connexion
formConnexion:
  path: /connexion/form
  controller: App\Controller\UserController::formConnexion

#Création fonction
createFonction:
  path: /fonction/create
  controller: App\Controller\FonctionController::createFonction

#Formulaire création fonction
formCreateFonction:
  path: /fonction/create/form
  controller: App\Controller\FonctionController::formCreateFonction

#Liste fonctions
listFonction:
  path: /fonction/list
  controller: App\Controller\FonctionController::listFonction